function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID0\" class=\"headerLeftMenuInActive\"><a id=\"aID0\" href=\"#\" OnMouseOver=\"link('','index',this)\" class=\"leftMenuLinkHeadInActive\">Default mainpage</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Default mainpage','"#"','','common/directoryBlue', { "onmouseover":"link('','index',this);" });
  treeLeftMenu.startParentNode('karel','"#"','','common/directoryBlue', { "onmouseover":"link('_dir','karel/karel0',this);" });
  treeLeftMenu.startParentNode('Structs','"#"','','common/structsBlue');
  treeLeftMenu.addNode('s_box','"#"','','common/struct', { "onmouseover":"link('_class','karel/s_box0',this);" });
  treeLeftMenu.addNode('s_robot','"#"','','common/struct', { "onmouseover":"link('_class','karel/s_robot0',this);" });
  treeLeftMenu.addNode('s_world','"#"','','common/struct', { "onmouseover":"link('_class','karel/s_world0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Functions','"#"','','common/functionsBlue');
  treeLeftMenu.addNode('areValid','"#"','','common/function', { "onmouseover":"link('_member','karel/areValid231090242',this);" });
  treeLeftMenu.addNode('areYouHere','"#"','','common/function', { "onmouseover":"link('_member','karel/areYouHere231090242',this);" });
  treeLeftMenu.addNode('avenues','"#"','','common/function', { "onmouseover":"link('_member','karel/avenues122',this);" });
  treeLeftMenu.addNode('beepers','"#"','','common/function', { "onmouseover":"link('_member','karel/beepers122',this);" });
  treeLeftMenu.addNode('beepersInBag','"#"','','common/function', { "onmouseover":"link('_member','karel/beepersInBag122',this);" });
  treeLeftMenu.addNode('beepersInBox','"#"','','common/function', { "onmouseover":"link('_member','karel/beepersInBox122',this);" });
  treeLeftMenu.addNode('checkBoxStatus','"#"','','common/function', { "onmouseover":"link('_member','karel/checkBoxStatus122',this);" });
  treeLeftMenu.addNode('checkRobotStatus','"#"','','common/function', { "onmouseover":"link('_member','karel/checkRobotStatus122',this);" });
  treeLeftMenu.addNode('close_World','"#"','','common/function', { "onmouseover":"link('_member','karel/close_World122',this);" });
  treeLeftMenu.addNode('closeBox','"#"','','common/function', { "onmouseover":"link('_member','karel/closeBox122',this);" });
  treeLeftMenu.addNode('clreol','"#"','','common/function', { "onmouseover":"link('_member','karel/clreol122',this);" });
  treeLeftMenu.addNode('clrscr','"#"','','common/function', { "onmouseover":"link('_member','karel/clrscr122',this);" });
  treeLeftMenu.addNode('create_Box','"#"','','common/function', { "onmouseover":"link('_member','karel/create_Box2515574380',this);" });
  treeLeftMenu.addNode('create_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel/create_Robot2608232773',this);" });
  treeLeftMenu.addNode('create_World','"#"','','common/function', { "onmouseover":"link('_member','karel/create_World86138908',this);" });
  treeLeftMenu.addNode('debug_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel/debug_Robot122',this);" });
  treeLeftMenu.addNode('debug_Robot_Off','"#"','','common/function', { "onmouseover":"link('_member','karel/debug_Robot_Off122',this);" });
  treeLeftMenu.addNode('debug_Robot_On','"#"','','common/function', { "onmouseover":"link('_member','karel/debug_Robot_On122',this);" });
  treeLeftMenu.addNode('delay','"#"','','common/function', { "onmouseover":"link('_member','karel/delay243606788',this);" });
  treeLeftMenu.addNode('face','"#"','','common/function', { "onmouseover":"link('_member','karel/face60979',this);" });
  treeLeftMenu.addNode('faceEast','"#"','','common/function', { "onmouseover":"link('_member','karel/faceEast122',this);" });
  treeLeftMenu.addNode('faceNorth','"#"','','common/function', { "onmouseover":"link('_member','karel/faceNorth122',this);" });
  treeLeftMenu.addNode('faceSouth','"#"','','common/function', { "onmouseover":"link('_member','karel/faceSouth122',this);" });
  treeLeftMenu.addNode('faceWest','"#"','','common/function', { "onmouseover":"link('_member','karel/faceWest122',this);" });
  treeLeftMenu.addNode('facing','"#"','','common/function', { "onmouseover":"link('_member','karel/facing60979',this);" });
  treeLeftMenu.addNode('facingEast','"#"','','common/function', { "onmouseover":"link('_member','karel/facingEast122',this);" });
  treeLeftMenu.addNode('facingNorth','"#"','','common/function', { "onmouseover":"link('_member','karel/facingNorth122',this);" });
  treeLeftMenu.addNode('facingSouth','"#"','','common/function', { "onmouseover":"link('_member','karel/facingSouth122',this);" });
  treeLeftMenu.addNode('facingWest','"#"','','common/function', { "onmouseover":"link('_member','karel/facingWest122',this);" });
  treeLeftMenu.addNode('fatal_Error','"#"','','common/function', { "onmouseover":"link('_member','karel/fatal_Error86138908',this);" });
  treeLeftMenu.addNode('frontIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel/frontIsClear122',this);" });
  treeLeftMenu.addNode('get_Error','"#"','','common/function', { "onmouseover":"link('_member','karel/get_Error122',this);" });
  treeLeftMenu.addNode('get_World','"#"','','common/function', { "onmouseover":"link('_member','karel/get_World231090242',this);" });
  treeLeftMenu.addNode('gotoxy','"#"','','common/function', { "onmouseover":"link('_member','karel/gotoxy231090242',this);" });
  treeLeftMenu.addNode('has_BEEPER','"#"','','common/function', { "onmouseover":"link('_member','karel/has_BEEPER231090242',this);" });
  treeLeftMenu.addNode('has_BEEPERS','"#"','','common/function', { "onmouseover":"link('_member','karel/has_BEEPERS231090242',this);" });
  treeLeftMenu.addNode('has_BOX','"#"','','common/function', { "onmouseover":"link('_member','karel/has_BOX231090242',this);" });
  treeLeftMenu.addNode('has_Error','"#"','','common/function', { "onmouseover":"link('_member','karel/has_Error122',this);" });
  treeLeftMenu.addNode('has_HWALL','"#"','','common/function', { "onmouseover":"link('_member','karel/has_HWALL231090242',this);" });
  treeLeftMenu.addNode('has_ROBOT','"#"','','common/function', { "onmouseover":"link('_member','karel/has_ROBOT802104044',this);" });
  treeLeftMenu.addNode('has_slot','"#"','','common/function', { "onmouseover":"link('_member','karel/has_slot231090242',this);" });
  treeLeftMenu.addNode('has_VWALL','"#"','','common/function', { "onmouseover":"link('_member','karel/has_VWALL231090242',this);" });
  treeLeftMenu.addNode('isEmptyBox','"#"','','common/function', { "onmouseover":"link('_member','karel/isEmptyBox122',this);" });
  treeLeftMenu.addNode('leftIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel/leftIsClear122',this);" });
  treeLeftMenu.addNode('move','"#"','','common/function', { "onmouseover":"link('_member','karel/move122',this);" });
  treeLeftMenu.addNode('nextToABeeper','"#"','','common/function', { "onmouseover":"link('_member','karel/nextToABeeper122',this);" });
  treeLeftMenu.addNode('nextToABox','"#"','','common/function', { "onmouseover":"link('_member','karel/nextToABox122',this);" });
  treeLeftMenu.addNode('nextToARobot','"#"','','common/function', { "onmouseover":"link('_member','karel/nextToARobot122',this);" });
  treeLeftMenu.addNode('openBox','"#"','','common/function', { "onmouseover":"link('_member','karel/openBox122',this);" });
  treeLeftMenu.addNode('pickBeeper','"#"','','common/function', { "onmouseover":"link('_member','karel/pickBeeper122',this);" });
  treeLeftMenu.addNode('pickBeeperFromBox','"#"','','common/function', { "onmouseover":"link('_member','karel/pickBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pullBeeperFromBox','"#"','','common/function', { "onmouseover":"link('_member','karel/pullBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pushBeeperIntoBox','"#"','','common/function', { "onmouseover":"link('_member','karel/pushBeeperIntoBox122',this);" });
  treeLeftMenu.addNode('putBeeper','"#"','','common/function', { "onmouseover":"link('_member','karel/putBeeper122',this);" });
  treeLeftMenu.addNode('putBeeperInBox','"#"','','common/function', { "onmouseover":"link('_member','karel/putBeeperInBox122',this);" });
  treeLeftMenu.addNode('read_World','"#"','','common/function', { "onmouseover":"link('_member','karel/read_World86138908',this);" });
  treeLeftMenu.addNode('remove_World','"#"','','common/function', { "onmouseover":"link('_member','karel/remove_World2680726270',this);" });
  treeLeftMenu.addNode('reset_World','"#"','','common/function', { "onmouseover":"link('_member','karel/reset_World122',this);" });
  treeLeftMenu.addNode('rightIsClear','"#"','','common/function', { "onmouseover":"link('_member','karel/rightIsClear122',this);" });
  treeLeftMenu.addNode('save_World','"#"','','common/function', { "onmouseover":"link('_member','karel/save_World86138908',this);" });
  treeLeftMenu.addNode('search_World','"#"','','common/function', { "onmouseover":"link('_member','karel/search_World802104044',this);" });
  treeLeftMenu.addNode('set_Error','"#"','','common/function', { "onmouseover":"link('_member','karel/set_Error60979',this);" });
  treeLeftMenu.addNode('set_Robot','"#"','','common/function', { "onmouseover":"link('_member','karel/set_Robot231090242',this);" });
  treeLeftMenu.addNode('set_Speed','"#"','','common/function', { "onmouseover":"link('_member','karel/set_Speed60979',this);" });
  treeLeftMenu.addNode('set_World','"#"','','common/function', { "onmouseover":"link('_member','karel/set_World802104044',this);" });
  treeLeftMenu.addNode('show_Board','"#"','','common/function', { "onmouseover":"link('_member','karel/show_Board252067370',this);" });
  treeLeftMenu.addNode('show_Error','"#"','','common/function', { "onmouseover":"link('_member','karel/show_Error86138908',this);" });
  treeLeftMenu.addNode('show_Screen','"#"','','common/function', { "onmouseover":"link('_member','karel/show_Screen246775574',this);" });
  treeLeftMenu.addNode('show_Text','"#"','','common/function', { "onmouseover":"link('_member','karel/show_Text86138908',this);" });
  treeLeftMenu.addNode('show_World','"#"','','common/function', { "onmouseover":"link('_member','karel/show_World122',this);" });
  treeLeftMenu.addNode('streets','"#"','','common/function', { "onmouseover":"link('_member','karel/streets122',this);" });
  treeLeftMenu.addNode('turnLeft','"#"','','common/function', { "onmouseover":"link('_member','karel/turnLeft122',this);" });
  treeLeftMenu.addNode('turnOff','"#"','','common/function', { "onmouseover":"link('_member','karel/turnOff122',this);" });
  treeLeftMenu.addNode('turnOn','"#"','','common/function', { "onmouseover":"link('_member','karel/turnOn122',this);" });
  treeLeftMenu.addNode('xAvenue','"#"','','common/function', { "onmouseover":"link('_member','karel/xAvenue122',this);" });
  treeLeftMenu.addNode('yStreet','"#"','','common/function', { "onmouseover":"link('_member','karel/yStreet122',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Attributes','"#"','','common/attributesBlue');
  treeLeftMenu.addNode('baseDelay','"#"','','common/variable', { "onmouseover":"link('_member','karel/baseDelay_38',this);" });
  treeLeftMenu.addNode('box_now','"#"','','common/variable', { "onmouseover":"link('_member','karel/box_now_74',this);" });
  treeLeftMenu.addNode('debug_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel/debug_txt0',this);" });
  treeLeftMenu.addNode('error_code','"#"','','common/variable', { "onmouseover":"link('_member','karel/error_code0',this);" });
  treeLeftMenu.addNode('error_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel/error_txt0',this);" });
  treeLeftMenu.addNode('has_debug','"#"','','common/variable', { "onmouseover":"link('_member','karel/has_debug0',this);" });
  treeLeftMenu.addNode('has_Debug','"#"','','common/variable', { "onmouseover":"link('_member','karel/has_Debug0',this);" });
  treeLeftMenu.addNode('has_Text','"#"','','common/variable', { "onmouseover":"link('_member','karel/has_Text_41',this);" });
  treeLeftMenu.addNode('message','"#"','','common/variable', { "onmouseover":"link('_member','karel/message0',this);" });
  treeLeftMenu.addNode('msg_board','"#"','','common/variable', { "onmouseover":"link('_member','karel/msg_board0',this);" });
  treeLeftMenu.addNode('msg_txt','"#"','','common/variable', { "onmouseover":"link('_member','karel/msg_txt0',this);" });
  treeLeftMenu.addNode('robot_now','"#"','','common/variable', { "onmouseover":"link('_member','karel/robot_now_73',this);" });
  treeLeftMenu.addNode('stepDelay','"#"','','common/variable', { "onmouseover":"link('_member','karel/stepDelay_39',this);" });
  treeLeftMenu.addNode('world_now','"#"','','common/variable', { "onmouseover":"link('_member','karel/world_now_72',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Types','"#"','','common/typesBlue');
  treeLeftMenu.addNode('box','"#"','','common/type', { "onmouseover":"link('_member','karel/box0',this);" });
  treeLeftMenu.addNode('ref_box','"#"','','common/type', { "onmouseover":"link('_member','karel/ref_box0',this);" });
  treeLeftMenu.addNode('ref_robot','"#"','','common/type', { "onmouseover":"link('_member','karel/ref_robot0',this);" });
  treeLeftMenu.addNode('ref_world','"#"','','common/type', { "onmouseover":"link('_member','karel/ref_world0',this);" });
  treeLeftMenu.addNode('robot','"#"','','common/type', { "onmouseover":"link('_member','karel/robot0',this);" });
  treeLeftMenu.addNode('world','"#"','','common/type', { "onmouseover":"link('_member','karel/world0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
document.write("<div class=\"paragraphLeftMenu\">Miscellaneous</div>\n");
document.write("<div id=\"divID26\" class=\"leftMenuTreeInActive\"><a id=\"aID26\" href=\"#\" OnMouseOver=\"link('_statsindex','common/statistics/index',this)\" class=\"leftMenuLinkInActive\">Statistics</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
