function WriteLeftMenu(divID, aID, divClassName, aClassName)
{
document.write("<div id=\"divID26\" class=\"headerLeftMenuInActive\"><a id=\"aID26\" href=\"#\" OnMouseOver=\"link('_statsindex','index',this)\" class=\"leftMenuLinkHeadInActive\">Statistics</a></div>\n");
document.write("<div id='leftmenutree' class='treeLeftMenu'>\n");
var treeLeftMenu = new TreeClass('treeLeftMenu', false);
treeLeftMenu.setTreeHeightDelta(-205);
treeLeftMenu.m_iDefaultExpandedLevel = 1;treeLeftMenu.setExpandCollapseNames('Expand All','Collapse All');
treeLeftMenu.startTree( true );
  treeLeftMenu.startParentNode('Default mainpage','"#"','','../directoryBlue', { "onmouseover":"link('','../../index',this);" });
  treeLeftMenu.startParentNode('karel','"#"','','../directoryBlue', { "onmouseover":"link('_dir','../../karel/karel0',this);" });
  treeLeftMenu.startParentNode('Structs','"#"','','../structsBlue');
  treeLeftMenu.addNode('s_box','"#"','','../struct', { "onmouseover":"link('_class','../../karel/s_box0',this);" });
  treeLeftMenu.addNode('s_robot','"#"','','../struct', { "onmouseover":"link('_class','../../karel/s_robot0',this);" });
  treeLeftMenu.addNode('s_world','"#"','','../struct', { "onmouseover":"link('_class','../../karel/s_world0',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Functions','"#"','','../functionsBlue');
  treeLeftMenu.addNode('areValid','"#"','','../function', { "onmouseover":"link('_member','../../karel/areValid231090242',this);" });
  treeLeftMenu.addNode('areYouHere','"#"','','../function', { "onmouseover":"link('_member','../../karel/areYouHere231090242',this);" });
  treeLeftMenu.addNode('avenues','"#"','','../function', { "onmouseover":"link('_member','../../karel/avenues122',this);" });
  treeLeftMenu.addNode('beepers','"#"','','../function', { "onmouseover":"link('_member','../../karel/beepers122',this);" });
  treeLeftMenu.addNode('beepersInBag','"#"','','../function', { "onmouseover":"link('_member','../../karel/beepersInBag122',this);" });
  treeLeftMenu.addNode('beepersInBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/beepersInBox122',this);" });
  treeLeftMenu.addNode('checkBoxStatus','"#"','','../function', { "onmouseover":"link('_member','../../karel/checkBoxStatus122',this);" });
  treeLeftMenu.addNode('checkRobotStatus','"#"','','../function', { "onmouseover":"link('_member','../../karel/checkRobotStatus122',this);" });
  treeLeftMenu.addNode('close_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/close_World122',this);" });
  treeLeftMenu.addNode('closeBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/closeBox122',this);" });
  treeLeftMenu.addNode('clreol','"#"','','../function', { "onmouseover":"link('_member','../../karel/clreol122',this);" });
  treeLeftMenu.addNode('clrscr','"#"','','../function', { "onmouseover":"link('_member','../../karel/clrscr122',this);" });
  treeLeftMenu.addNode('create_Box','"#"','','../function', { "onmouseover":"link('_member','../../karel/create_Box2515574380',this);" });
  treeLeftMenu.addNode('create_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel/create_Robot2608232773',this);" });
  treeLeftMenu.addNode('create_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/create_World86138908',this);" });
  treeLeftMenu.addNode('debug_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel/debug_Robot122',this);" });
  treeLeftMenu.addNode('debug_Robot_Off','"#"','','../function', { "onmouseover":"link('_member','../../karel/debug_Robot_Off122',this);" });
  treeLeftMenu.addNode('debug_Robot_On','"#"','','../function', { "onmouseover":"link('_member','../../karel/debug_Robot_On122',this);" });
  treeLeftMenu.addNode('delay','"#"','','../function', { "onmouseover":"link('_member','../../karel/delay243606788',this);" });
  treeLeftMenu.addNode('face','"#"','','../function', { "onmouseover":"link('_member','../../karel/face60979',this);" });
  treeLeftMenu.addNode('faceEast','"#"','','../function', { "onmouseover":"link('_member','../../karel/faceEast122',this);" });
  treeLeftMenu.addNode('faceNorth','"#"','','../function', { "onmouseover":"link('_member','../../karel/faceNorth122',this);" });
  treeLeftMenu.addNode('faceSouth','"#"','','../function', { "onmouseover":"link('_member','../../karel/faceSouth122',this);" });
  treeLeftMenu.addNode('faceWest','"#"','','../function', { "onmouseover":"link('_member','../../karel/faceWest122',this);" });
  treeLeftMenu.addNode('facing','"#"','','../function', { "onmouseover":"link('_member','../../karel/facing60979',this);" });
  treeLeftMenu.addNode('facingEast','"#"','','../function', { "onmouseover":"link('_member','../../karel/facingEast122',this);" });
  treeLeftMenu.addNode('facingNorth','"#"','','../function', { "onmouseover":"link('_member','../../karel/facingNorth122',this);" });
  treeLeftMenu.addNode('facingSouth','"#"','','../function', { "onmouseover":"link('_member','../../karel/facingSouth122',this);" });
  treeLeftMenu.addNode('facingWest','"#"','','../function', { "onmouseover":"link('_member','../../karel/facingWest122',this);" });
  treeLeftMenu.addNode('fatal_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel/fatal_Error86138908',this);" });
  treeLeftMenu.addNode('frontIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel/frontIsClear122',this);" });
  treeLeftMenu.addNode('get_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel/get_Error122',this);" });
  treeLeftMenu.addNode('get_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/get_World231090242',this);" });
  treeLeftMenu.addNode('gotoxy','"#"','','../function', { "onmouseover":"link('_member','../../karel/gotoxy231090242',this);" });
  treeLeftMenu.addNode('has_BEEPER','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_BEEPER231090242',this);" });
  treeLeftMenu.addNode('has_BEEPERS','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_BEEPERS231090242',this);" });
  treeLeftMenu.addNode('has_BOX','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_BOX231090242',this);" });
  treeLeftMenu.addNode('has_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_Error122',this);" });
  treeLeftMenu.addNode('has_HWALL','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_HWALL231090242',this);" });
  treeLeftMenu.addNode('has_ROBOT','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_ROBOT802104044',this);" });
  treeLeftMenu.addNode('has_slot','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_slot231090242',this);" });
  treeLeftMenu.addNode('has_VWALL','"#"','','../function', { "onmouseover":"link('_member','../../karel/has_VWALL231090242',this);" });
  treeLeftMenu.addNode('isEmptyBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/isEmptyBox122',this);" });
  treeLeftMenu.addNode('leftIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel/leftIsClear122',this);" });
  treeLeftMenu.addNode('move','"#"','','../function', { "onmouseover":"link('_member','../../karel/move122',this);" });
  treeLeftMenu.addNode('nextToABeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel/nextToABeeper122',this);" });
  treeLeftMenu.addNode('nextToABox','"#"','','../function', { "onmouseover":"link('_member','../../karel/nextToABox122',this);" });
  treeLeftMenu.addNode('nextToARobot','"#"','','../function', { "onmouseover":"link('_member','../../karel/nextToARobot122',this);" });
  treeLeftMenu.addNode('openBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/openBox122',this);" });
  treeLeftMenu.addNode('pickBeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel/pickBeeper122',this);" });
  treeLeftMenu.addNode('pickBeeperFromBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/pickBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pullBeeperFromBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/pullBeeperFromBox122',this);" });
  treeLeftMenu.addNode('pushBeeperIntoBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/pushBeeperIntoBox122',this);" });
  treeLeftMenu.addNode('putBeeper','"#"','','../function', { "onmouseover":"link('_member','../../karel/putBeeper122',this);" });
  treeLeftMenu.addNode('putBeeperInBox','"#"','','../function', { "onmouseover":"link('_member','../../karel/putBeeperInBox122',this);" });
  treeLeftMenu.addNode('read_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/read_World86138908',this);" });
  treeLeftMenu.addNode('remove_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/remove_World2680726270',this);" });
  treeLeftMenu.addNode('reset_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/reset_World122',this);" });
  treeLeftMenu.addNode('rightIsClear','"#"','','../function', { "onmouseover":"link('_member','../../karel/rightIsClear122',this);" });
  treeLeftMenu.addNode('save_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/save_World86138908',this);" });
  treeLeftMenu.addNode('search_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/search_World802104044',this);" });
  treeLeftMenu.addNode('set_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel/set_Error60979',this);" });
  treeLeftMenu.addNode('set_Robot','"#"','','../function', { "onmouseover":"link('_member','../../karel/set_Robot231090242',this);" });
  treeLeftMenu.addNode('set_Speed','"#"','','../function', { "onmouseover":"link('_member','../../karel/set_Speed60979',this);" });
  treeLeftMenu.addNode('set_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/set_World802104044',this);" });
  treeLeftMenu.addNode('show_Board','"#"','','../function', { "onmouseover":"link('_member','../../karel/show_Board252067370',this);" });
  treeLeftMenu.addNode('show_Error','"#"','','../function', { "onmouseover":"link('_member','../../karel/show_Error86138908',this);" });
  treeLeftMenu.addNode('show_Screen','"#"','','../function', { "onmouseover":"link('_member','../../karel/show_Screen246775574',this);" });
  treeLeftMenu.addNode('show_Text','"#"','','../function', { "onmouseover":"link('_member','../../karel/show_Text86138908',this);" });
  treeLeftMenu.addNode('show_World','"#"','','../function', { "onmouseover":"link('_member','../../karel/show_World122',this);" });
  treeLeftMenu.addNode('streets','"#"','','../function', { "onmouseover":"link('_member','../../karel/streets122',this);" });
  treeLeftMenu.addNode('turnLeft','"#"','','../function', { "onmouseover":"link('_member','../../karel/turnLeft122',this);" });
  treeLeftMenu.addNode('turnOff','"#"','','../function', { "onmouseover":"link('_member','../../karel/turnOff122',this);" });
  treeLeftMenu.addNode('turnOn','"#"','','../function', { "onmouseover":"link('_member','../../karel/turnOn122',this);" });
  treeLeftMenu.addNode('xAvenue','"#"','','../function', { "onmouseover":"link('_member','../../karel/xAvenue122',this);" });
  treeLeftMenu.addNode('yStreet','"#"','','../function', { "onmouseover":"link('_member','../../karel/yStreet122',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Attributes','"#"','','../attributesBlue');
  treeLeftMenu.addNode('baseDelay','"#"','','../variable', { "onmouseover":"link('_member','../../karel/baseDelay_38',this);" });
  treeLeftMenu.addNode('box_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel/box_now_74',this);" });
  treeLeftMenu.addNode('debug_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel/debug_txt0',this);" });
  treeLeftMenu.addNode('error_code','"#"','','../variable', { "onmouseover":"link('_member','../../karel/error_code0',this);" });
  treeLeftMenu.addNode('error_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel/error_txt0',this);" });
  treeLeftMenu.addNode('has_debug','"#"','','../variable', { "onmouseover":"link('_member','../../karel/has_debug0',this);" });
  treeLeftMenu.addNode('has_Debug','"#"','','../variable', { "onmouseover":"link('_member','../../karel/has_Debug0',this);" });
  treeLeftMenu.addNode('has_Text','"#"','','../variable', { "onmouseover":"link('_member','../../karel/has_Text_41',this);" });
  treeLeftMenu.addNode('message','"#"','','../variable', { "onmouseover":"link('_member','../../karel/message0',this);" });
  treeLeftMenu.addNode('msg_board','"#"','','../variable', { "onmouseover":"link('_member','../../karel/msg_board0',this);" });
  treeLeftMenu.addNode('msg_txt','"#"','','../variable', { "onmouseover":"link('_member','../../karel/msg_txt0',this);" });
  treeLeftMenu.addNode('robot_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel/robot_now_73',this);" });
  treeLeftMenu.addNode('stepDelay','"#"','','../variable', { "onmouseover":"link('_member','../../karel/stepDelay_39',this);" });
  treeLeftMenu.addNode('world_now','"#"','','../variable', { "onmouseover":"link('_member','../../karel/world_now_72',this);" });
treeLeftMenu.endParentNode();
  treeLeftMenu.startParentNode('Types','"#"','','../typesBlue');
  treeLeftMenu.addNode('box','"#"','','../type', { "onmouseover":"link('_member','../../karel/box0',this);" });
  treeLeftMenu.addNode('ref_box','"#"','','../type', { "onmouseover":"link('_member','../../karel/ref_box0',this);" });
  treeLeftMenu.addNode('ref_robot','"#"','','../type', { "onmouseover":"link('_member','../../karel/ref_robot0',this);" });
  treeLeftMenu.addNode('ref_world','"#"','','../type', { "onmouseover":"link('_member','../../karel/ref_world0',this);" });
  treeLeftMenu.addNode('robot','"#"','','../type', { "onmouseover":"link('_member','../../karel/robot0',this);" });
  treeLeftMenu.addNode('world','"#"','','../type', { "onmouseover":"link('_member','../../karel/world0',this);" });
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endParentNode();
treeLeftMenu.endTree();
treeLeftMenu.readStateFromCookie();
document.write("</div>\n");
document.write("<div class=\"paragraphLeftMenu\">Pages</div>\n");
document.write("<div id=\"divID228\" class=\"leftMenuTreeInActive\"><a id=\"aID228\" href=\"#\" OnMouseOver=\"link('_statsgeneral','stats_general',this)\" class=\"leftMenuLinkInActive\">General</a></div>\n");
document.write("<div id=\"divID229\" class=\"leftMenuTreeInActive\"><a id=\"aID229\" href=\"#\" OnMouseOver=\"link('_statsundoc','stats_undoc',this)\" class=\"leftMenuLinkInActive\">Undocumented</a></div>\n");
document.write("<div id=\"divID230\" class=\"leftMenuTreeInActive\"><a id=\"aID230\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_msg',this)\" class=\"leftMenuLinkInActive\">Msg-Messages</a></div>\n");
document.write("<div id=\"divID231\" class=\"leftMenuTreeInActive\"><a id=\"aID231\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_warn',this)\" class=\"leftMenuLinkInActive\">Msg-Warnings</a></div>\n");
document.write("<div id=\"divID232\" class=\"leftMenuTreeInActive\"><a id=\"aID232\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_err',this)\" class=\"leftMenuLinkInActive\">Msg-Errors</a></div>\n");
document.write("<div id=\"divID233\" class=\"leftMenuTreeInActive\"><a id=\"aID233\" href=\"#\" OnMouseOver=\"link('_statsmsg','stats_msg_dbg',this)\" class=\"leftMenuLinkInActive\">Msg-Debug</a></div>\n");
if(divID != "" && aID != "")
{
  var elemDiv = document.getElementById(divID);
  var elemA = document.getElementById(aID);
  if (elemDiv != undefined && elemA != undefined ) { // this is needed to abvoid crashing js on some memberpages 
    elemDiv.className = divClassName;
    elemA.className = aClassName;
  }
}
}
